### ISSUE TITLE
Error when trying to mark duplicate praise

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/praise#162] opened 2022-03-15 15:38 UTC
While quantifying I try to mark a praise as duplicate, I have already marked another praise a duplicate of this one and I receive an error 

![image](https://user-images.githubusercontent.com/67759413/158414549-03675581-b3e6-44ce-b758-9afde12a8b12.png)

I try to mark the duplicate and I receive this notification - 

![image](https://user-images.githubusercontent.com/67759413/158414768-43904cf4-c0a6-433f-9652-5826e5c9322a.png)

what is preventing me from marking this duplicate?

**Comment by kristoferlund** [comment] 2022-03-15 19:47
@divine-comedian Could you try  another combination? Does this work?

Mark 8bc1 as dupe of 8be6
Mark 8bde as dupe of 8be6

**Comment by divine-comedian** [comment] 2022-03-15 22:37
> @divine-comedian Could you try another combination? Does this work?
> 
> Mark 8bc1 as dupe of 8be6 Mark 8bde as dupe of 8be6

I can mark 8bc1 as dupe of 8be6 but when I mark 8bde as dupe of 8be6 I receive the same error.

**Comment by mattyg** [comment] 2022-04-04 15:56
In #221 we did a minor refactor of praise/controllers/quantify to clarify logic flow.

 was not actually able to reproduce https://github.com/CommonsBuild/praise/issues/162. I suggest we close the ticket and re-open if the issue arises again.

Resolves https://github.com/CommonsBuild/praise/issues/162

**Closed by mattyg** 2022-04-04 15:56 UTC
Labels: bug
